name: frontend
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_client: ^2.0.0-alpha
  angel_websocket: ^2.0.0-alpha
  angular: ">=5.0.0 <5.1.0"
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha
  shared:
    path: ../shared
dev_dependencies:
  build_runner: 
  build_web_compilers: ^0.4.0