name: shared
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
  angel_validate: ^2.0.0
  meta: ^1.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0