name: backend
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  angel_production: ^1.0.0-alpha
  angel_proxy: ^2.0.0
  angel_static: ^2.0.0
  angel_validate: ^2.0.0
  angel_websocket: ^2.0.0-alpha
  shared:
    path: ../shared
